# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "github-runner"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.network "private_network", ip: "192.168.60.101"
  config.vm.network "forwarded_port", guest: 22, host: 2210, id: "ssh"
  config.ssh.forward_agent = true
end